version: '3.7'

services:
  message-system:
    container_name: message-system
    env_file:
      - .env
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    networks:
      - gateway
  postgres:
    container_name: postgres
    image: postgres:12
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    networks:
      - gateway
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
        container_name: redis
        image: 'redislabs/redismod'
        ports:
          - '6379:6379'
        networks:
          - gateway

networks:
  gateway:

volumes:
  pgdata: {}